<a href="https://colab.research.google.com/github/feniltailor22/Machine-Learning-Projects/blob/main/ADAboost_and_Bagging_Implimentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.datasets import load_breast_cancer
cancer= load_breast_cancer()

In [ ]:
cancer

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [ ]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
#converting dictionary input data into dataframe
df_feat= pd.DataFrame(data=cancer['data'],columns=cancer['feature_names'])
df_feat.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [ ]:
#dataframe for the output(target)
df_target= pd.DataFrame(data=cancer['target'],columns=['Cancer']) #column name is newly given
df_target.head()

Cancer
0       0
1       0
2       0
3       0
4       0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(df_feat,df_target,test_size=0.30,random_state=101)

In [ ]:
#Train our Model on SVM (without ADAboost)
from sklearn.svm import SVC

In [ ]:
model_svm= SVC()
model_svm.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
prediction_svm= model_svm.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,prediction_svm))

              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171



In [ ]:
print(confusion_matrix(y_test,prediction_svm))

[[ 56  10]
 [  3 102]]


In [ ]:
#Training ADABoost on SVM

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
svm_ada= AdaBoostClassifier(base_estimator=SVC(),n_estimators=100,algorithm='SAMME')

#base_estimator is instance of your Training model.
#n_estimators= the number of Weak Learners.
##Other than DecisionTreeClassifier we have to use SAMME (Stagewise Additive Modeling, since we update the weights of sample) as an algorithm instead of SAMME.R.

#SAMME.R uses the probability estimates to update the additive model, while SAMME uses the classifications only. 
#The SAMME.R algorithm typically converges faster than SAMME, achieving a lower test error with fewer boosting iterations.

#SAMME is a discrete-valued algorithm, meaning that it outputs either 0 or 1. 
#SAMME.R uses class probabilities, Meaning that it outputs the probability of a sample belonging to a class.

In [ ]:
svm_ada.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                      class_weight=None, coef0=0.0,
                                      decision_function_shape='ovr', degree=3,
                                      gamma='scale', kernel='rbf', max_iter=-1,
                                      probability=False, random_state=None,
                                      shrinking=True, tol=0.001,
                                      verbose=False),
                   learning_rate=1.0, n_estimators=100, random_state=None)

In [ ]:
svm_ada_pred= svm_ada.predict(X_test)

In [ ]:
print(classification_report(y_test,svm_ada_pred))

              precision    recall  f1-score   support

           0       0.96      0.71      0.82        66
           1       0.84      0.98      0.91       105

    accuracy                           0.88       171
   macro avg       0.90      0.85      0.86       171
weighted avg       0.89      0.88      0.87       171



In [ ]:
print(confusion_matrix(y_test,svm_ada_pred))

[[ 47  19]
 [  2 103]]


In [ ]:
#SVM and ADAboost don't perform better in combination as both algorithms are complicated.

In [ ]:
#Train our model on DecisionTree (Without ADAboost)
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt= DecisionTreeClassifier()

In [ ]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
pred_dt= dt.predict(X_test)

In [ ]:
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        66
           1       0.93      0.93      0.93       105

    accuracy                           0.92       171
   macro avg       0.91      0.91      0.91       171
weighted avg       0.92      0.92      0.92       171



In [ ]:
print(confusion_matrix(y_test,pred_dt))

[[59  7]
 [ 7 98]]


In [ ]:
#Training DecisionTree with ADAboost

In [ ]:
dt_ada= AdaBoostClassifier(n_estimators=100)
#If the base_estimator is None then it is considered as DecisionTreeClassifier(max_depth=1). (default)
#Algorithm used in DecisionTreeClassifier is SAMME.R (R stands for Real). (default)
#Other than DecisionTreeClassifier we have to use SAMME as an algorithm instead of SAMME.R.

In [ ]:
dt_ada.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=None)

In [ ]:
dt_ada_pred= dt_ada.predict(X_test)

In [ ]:
print(classification_report(y_test,dt_ada_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.95        66
           1       0.96      0.97      0.97       105

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [ ]:
print(confusion_matrix(y_test,dt_ada_pred))

[[ 62   4]
 [  3 102]]


In [ ]:
#Training Model on RandomForest (Without ADAboost)
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc= RandomForestClassifier(criterion='entropy',random_state=0)

In [ ]:
rfc.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
rfc_pred= rfc.predict(X_test)

In [ ]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        66
           1       0.95      0.97      0.96       105

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [ ]:
print(confusion_matrix(y_test,rfc_pred))

[[ 61   5]
 [  3 102]]


In [ ]:
#Implementing Bagging

In [ ]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
bag= BaggingClassifier(n_estimators=100, max_samples=0.8, random_state=1)

# max_samples= The number of samples to draw from X to train each base estimator.
# maximum number of samples taken in each new subset. Here it is 80%.

In [ ]:
bag.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_bagging.py:645: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=0.8, n_estimators=100,
                  n_jobs=None, oob_score=False, random_state=1, verbose=0,
                  warm_start=False)

In [ ]:
bag_pred= bag.predict(X_test) 

In [ ]:
print(classification_report(y_test,bag_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        66
           1       0.96      0.96      0.96       105

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [ ]:
print(confusion_matrix(y_test,bag_pred))

[[ 62   4]
 [  4 101]]


In [ ]:
#Traing RandomForestClassifier with ADAboost

In [ ]:
rfc_ada= AdaBoostClassifier(base_estimator=RandomForestClassifier(),n_estimators=100,algorithm='SAMME')

In [ ]:
rfc_ada.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                         

In [ ]:
rfc_ada_pred= rfc_ada.predict(X_test)

In [ ]:
print(classification_report(y_test,rfc_ada_pred))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        66
           1       0.95      0.96      0.96       105

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171



In [ ]:
print(confusion_matrix(y_test,rfc_ada_pred))

[[ 61   5]
 [  4 101]]
